name: mruby
title: Lightweight Ruby
description: >- # this means to ignore newlines until "markdown:"
  mruby is the lightweight implementation of the Ruby language complying to (part of) the ISO standard.
  mruby can be linked and embedded within your application. We provide the interpreter program "mruby" and the
  interactive mruby shell "mirb" as examples. You can also compile Ruby programs into compiled byte code using the
  mruby compiler "mrbc". All those tools reside in the "bin" directory. "mrbc" is also able to generate compiled byte
  code in a C source file, see the "mrbtest" program under the "test" directory for an example.
markdown: kramdown
highlighter: rouge
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
site_logo: "/assets/images/site-logo.png" # Site wide logo

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - assets/foundation/node_modules/
  - assets/foundation/scss/
  - assets/foundation/.babelrc
  - assets/foundation/.gitignore
  - assets/foundation/config.yml
  - assets/foundation/gulpfile.babel.js
  - assets/foundation/package.json
  - assets/foundation/readme.md
  - assets/foundation/yarn.lock