title: mRuby
email: your-email@example.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - assets/foundation/node_modules/
  - assets/foundation/scss/
  - assets/foundation/.babelrc
  - assets/foundation/.gitignore
  - assets/foundation/config.yml
  - assets/foundation/gulpfile.babel.js
  - assets/foundation/package.json
  - assets/foundation/readme.md
  - assets/foundation/yarn.lock